# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus ตัวเอง
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # RescuePaw Backend
  - job_name: 'rescuepaw-backend'
    static_configs:
      - targets: 
          - 'backend1:3000'
          - 'backend2:3000'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # cAdvisor (Container Metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s


    alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# เพิ่มไฟล์ alert rules
rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    
  - job_name: 'rescuepaw-backend'
    static_configs:
      - targets: 
          - 'backend1:3000'
          - 'backend2:3000'
    metrics_path: '/metrics'
    scrape_interval: 15s
    
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
