services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    platform: linux/amd64
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - volume_loan:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - network_devtools

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    platform: linux/amd64
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - network_devtools

volumes:
  volume_loan:
    name: volume_loan
    driver: local

networks:
  network_devtools:
    name: network_devtools
    driver: bridge